# I. Numpy

### Импортируйте NumPy

In [2]:
 import numpy as np

### Создайте одномерный массив размера 10, заполненный нулями и пятым элемент равным 1. Трансформируйте в двумерный массив.

In [3]:
a = np.zeros(10)
print(a)
a[5] = 1
print(a)
a = a.reshape((2,-1))
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


### Создайте одномерный массив со значениями от 10 до 49 и разверните его (первый элемент становится последним). Найдите в нем все четные элементы.

In [43]:
a = np.arange(10,50)
print(a)
a = np.flip(a)
print(a)
a = a[a % 2 == 0]
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[48 46 44 42 40 38 36 34 32 30 28 26 24 22 20 18 16 14 12 10]


### Создайте двумерный массив 3x3 со значениями от 0 до 8

In [21]:
a = np.arange(0,9)
a = a.reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Создайте массив 4x3x2 со случайными значениями. Найти его минимум и максимум.

In [42]:
a = np.random.rand(4,3,2)
print(a)
a_min = np.min(a)
a_max = np.max(a)
print(a_min,a_max)

[[[0.00833144 0.26413877]
  [0.169913   0.70807373]
  [0.7666941  0.98679896]]

 [[0.74236171 0.49177374]
  [0.34645467 0.30038435]
  [0.07762749 0.0808531 ]]

 [[0.07313633 0.93684816]
  [0.39242037 0.65489756]
  [0.93447731 0.99070535]]

 [[0.27129628 0.03829407]
  [0.00276585 0.80268101]
  [0.54029456 0.01022377]]]
0.0027658524293979747 0.9907053509298065


### Создайте два двумерных массива размерами 6x4 и 4x3 и произведите их матричное умножение. 

In [4]:
a = np.random.randint(0,100,(6,4))
print(a)
b = np.random.randint(0,100,(4,3))
print(b)
c = np.matmul(a, b)
print(c)

[[16 73 59 21]
 [99  3 98 53]
 [39 41 16 22]
 [19 89 28 65]
 [38 72 83 64]
 [50  4 95 98]]
[[28 18 89]
 [76 65 13]
 [20  7 62]
 [64 72 53]]
[[ 8520  6958  7144]
 [ 8352  6479 17735]
 [ 5936  5063  6162]
 [12016 11003  8029]
 [12292 10553 12856]
 [ 9876  8881 15586]]


### Создайте случайный двумерный массив 7x7, найти у него среднее и стандартное оклонение. Нормализуйте этот массив.

In [9]:
a = np.random.randint(0,100,(7,7))
print(a)
b = np.mean(a)
print(b)
c = np.std(a)
print(c)
a_norm = (a - a. min ())/ (a. max () - a. min ())
print(a_norm)

[[67 55 62 29 11 93  2]
 [75 30 35  7 75 22 24]
 [55 66 81 32 72 57  7]
 [15 65  6 36 22 74 93]
 [51 71  4 35 96 49 40]
 [59 25 47 74 69 65 16]
 [ 2 58 66 81 32 30 79]]
47.285714285714285
26.847262620313487
[[0.69148936 0.56382979 0.63829787 0.28723404 0.09574468 0.96808511
  0.        ]
 [0.77659574 0.29787234 0.35106383 0.05319149 0.77659574 0.21276596
  0.23404255]
 [0.56382979 0.68085106 0.84042553 0.31914894 0.74468085 0.58510638
  0.05319149]
 [0.13829787 0.67021277 0.04255319 0.36170213 0.21276596 0.76595745
  0.96808511]
 [0.5212766  0.73404255 0.0212766  0.35106383 1.         0.5
  0.40425532]
 [0.60638298 0.24468085 0.4787234  0.76595745 0.71276596 0.67021277
  0.14893617]
 [0.         0.59574468 0.68085106 0.84042553 0.31914894 0.29787234
  0.81914894]]


# II. Pandas

### Импортируйте: pandas, matplotlib, seaborn

In [4]:
pip install matplotlib

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.1 -> 24.2
[notice] To update, run: D:\OTUS\Brand_public\.venv\Scripts\python.exe -m pip install --upgrade pip


In [12]:
pip install seaborn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.1 -> 24.2
[notice] To update, run: D:\OTUS\Brand_public\.venv\Scripts\python.exe -m pip install --upgrade pip


In [13]:
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

### Загрузите датасет Tips из набора датасетов seaborn

In [14]:
Tips = sns.load_dataset("tips")
Tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

### Посмотрите на первые 5 строчек

In [11]:
Tips.head(5)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

### Узнайте сколько всего строчек и колонок в данных

In [32]:
Tips.shape

(244, 7)

### Проверьте есть ли пропуски в данных

In [20]:
Tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [21]:
Tips.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

### Посмотрите на распределение числовых признаков

In [22]:
Tips.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

### Найдите максимальное значение 'total_bill'

In [23]:
Tips['total_bill'].max()

50.81

### Найдите количество курящих людей

### Узнайте какой средний 'total_bill' в зависимости от 'day'

### Отберите строчки с 'total_bill' больше медианы и узнайте какой средний 'tip' в зависимости от 'sex'

### Преобразуйте признак 'smoker' в бинарный (0-No, 1-Yes)

# III. Visualization

### Постройте гистограмму распределения признака 'total_bill'

### Постройте scatterplot, представляющий взаимосвязь между признаками 'total_bill' и 'tip'

### Постройте pairplot

### Постройте график взаимосвязи между признаками 'total_bill' и 'day'

### Постройте две гистограммы распределения признака 'tip' в зависимости от категорий 'time'

### Постройте два графика scatterplot, представляющих взаимосвязь между признаками 'total_bill' и 'tip' один для Male, другой для Female и раскрасьте точки в зависимоти от признака 'smoker'

## Сделайте выводы по анализу датасета и построенным графикам. По желанию можете продолжить анализ данных и также отразить это в выводах.